### ISSUE TITLE
Connection issues referencing cemerick/drawbridge/client

### ISSUE THREAD

**Issue by Folcon** [nrepl/drawbridge#25] opened 2018-06-15 15:08 UTC
I've managed to setup drawbridge using the dependency below in my project.clj:
```
[nrepl/drawbridge "0.1.1"]
```

I believe I can connect to it when I navigate to the `/repl` address on localhost.

However, if I try:
```
lein repl :connect http://127.0.0.1:3000/repl
```
I get:
```
Connecting to nREPL at http://127.0.0.1:3000/repl
java.io.FileNotFoundException: Could not locate cemerick/drawbridge/client__init.class or cemerick/drawbridge/client.clj on classpath.
 at clojure.lang.RT.load (RT.java:456)
    clojure.lang.RT.load (RT.java:419)
    clojure.core$load$fn__5677.invoke (core.clj:5893)
    clojure.core$load.invokeStatic (core.clj:5892)
    clojure.core$load.doInvoke (core.clj:5876)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invokeStatic (core.clj:5697)
    clojure.core$load_one.invoke (core.clj:5692)
    clojure.core$load_lib$fn__5626.invoke (core.clj:5737)
    clojure.core$load_lib.invokeStatic (core.clj:5736)
    clojure.core$load_lib.doInvoke (core.clj:5717)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$load_libs.invokeStatic (core.clj:5774)
    clojure.core$load_libs.doInvoke (core.clj:5758)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$require.invokeStatic (core.clj:5796)
    clojure.core$require.doInvoke (core.clj:5796)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    leiningen.repl$client.invokeStatic (repl.clj:260)
    leiningen.repl$client.invoke (repl.clj:258)
    leiningen.repl$repl.invokeStatic (repl.clj:312)
    leiningen.repl$repl.doInvoke (repl.clj:267)
    clojure.lang.RestFn.invoke (RestFn.java:442)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__4667.doInvoke (main.clj:284)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:340)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.core.main$_main$fn__4734.invoke (main.clj:420)
    leiningen.core.main$_main.invokeStatic (main.clj:411)
    leiningen.core.main$_main.doInvoke (main.clj:408)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:482)
    clojure.lang.Var.invoke (Var.java:401)
    clojure.lang.AFn.applyToHelper (AFn.java:171)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```
Is the clojars jar file referencing it by any chance?

**Comment by Folcon** [comment] 2018-06-15 15:52
Even entirely disabling my `.lein/profiles.clj` throws the same exception.

**Comment by Folcon** [comment] 2018-06-16 00:05
Ok, I've worked out the issue, but I'm not sure what the fix is? There's a required dependency on:
```
:plugins [[com.cemerick/drawbridge "0.0.7"]]
```
[It's documented here](https://github.com/technomancy/leiningen/issues/2370) that adding the entry above to my plugins `project.clj` will work.

**Comment by Vinai** [comment] 2018-06-30 07:29
Thanks for digging this up @Folcon. I can confirm that the issue exists with `nrepl/drawbridge "0.1.1"`, both if it is a sole dependency, and also when it is also added as a `:plugins` entry.
If I use `com.cemerick/drawbridge "0.0.7"` for both it works.

**Comment by Folcon** [comment] 2018-06-30 11:00
@Vinai Ok, do you want to just document that in the readme? Or is the intention to change it so that it no longer depends on `com.cemerick/drawbridge "0.0.7"`?

**Comment by Vinai** [comment] 2018-06-30 11:09
I have no idea what the right strategy is as I'm only a consumer of the library (well.. not me, my code is). I was commenting in order to give this issue a bump.
Hopefully the dependency will be removed, but I don't feel qualified to work on a PR myself.

**Comment by Folcon** [comment] 2018-06-30 11:18
Apologies @Vinai, thank you for the bump.

**Comment by bbatsov** [comment] 2018-07-07 06:40
You're supposed to use nrepl/drawbridge together with nrepl/nrepl. Unfortunately lein and boot still haven't merged my PRs replacing the legacy clojure.tools.nrepl with the "new" nREPL. I'll likely have to create some boot/lein plugins for this to remedy the situation in the interim.

**Comment by bbatsov** [comment] 2018-07-07 06:40
You can support the merger of https://github.com/technomancy/leiningen/pull/2444 https://github.com/boot-clj/boot/pull/703

**Comment by bbatsov** [comment] 2018-07-21 22:44
See also https://github.com/nrepl/lein-nrepl (it's a replacement for `lein repl` until the nREPL dep is bumped there).

**Comment by Vinai** [comment] 2018-07-22 20:05
Thank you for this, I'll check it out tomorrow!

**Closed** 2018-10-15 15:57 UTC

**Comment by Folcon** [comment] 2018-10-16 17:27
I didn't want to reopen the issue as I wasn't sure what state it was in, but just for clarity @bbatsov, now that technomancy/leiningen#2444 is merged, do I just update leiningen and it should work?

I tried using the `lein-nrepl` that you linked and the command:
```
lein repl :connect https://<user>:<pass>@<host>/repl
```
Command which I can get working doesn't function as:
```
lein nrepl :connect https://<user>:<pass>@<host>/repl
```

**Comment by bbatsov** [comment] 2018-10-17 07:52
@Folcon You'll need to use the development version of Lein (that's going to become 2.8.2 at some point). Unfortunately they haven't had a release since the PR was merged.

> Command which I can get working doesn't function as:

I didn't really think of adding support for drawbridge to `lein-nrepl`, but that's certainly doable.

**Comment by Folcon** [comment] 2018-10-20 17:12
@bbatsov That's frustrating, from what I can tell they haven't had a release for over a year.
For anyone else who might find this useful:
I've currently got the `leiningen-2.8.2-SNAPSHOT-standalone.jar` build working by installing the master separately from Homebrew [using the instructions here](https://github.com/technomancy/leiningen/blob/stable/CONTRIBUTING.md#uberjar-from-master)

However I seem to have been stuck at the final steps:
```
ArityException Wrong number of args (0) passed to: client/ring-client-transport/read--1263
        nrepl.transport/fn-transport/fn--8332 (transport.clj:39)
        clojure.core/binding-conveyor-fn/fn--4676 (core.clj:1938)
        java.util.concurrent.FutureTask.run (FutureTask.java:266)
        java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
        java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
        java.lang.Thread.run (Thread.java:745)
```
I'm only using:
```
[nrepl/drawbridge "0.1.3"]
```
Having removed the reference to `com.cemerick/drawbridge`.

Right now, really unclear where the problem is coming from, is there a 0 arity version of `client/ring-client-transport/read` that's just no longer being defined?

How hard would you say adding drawbridge support to `lein-nrepl` is? Is it something I can put together a PR for?

**Comment by bbatsov** [comment] 2018-10-20 18:32
> Right now, really unclear where the problem is coming from, is there a 0 arity version of client/ring-client-transport/read that's just no longer being defined?

Hmm, let me look into this. I don't recall such an API change. 

> How hard would you say adding drawbridge support to lein-nrepl is? Is it something I can put together a PR for?

That should be very simple. A PR would be welcome.
